### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by kozi** [menatwork-ia/realurl#3]
The extension does not seem to be PHP7 compatible.
Everything works fine with PHP 5.6 but with PHP7 activated:

contao 3.5.15
menatwork/realurl 1.3.4

```
Fatal error: Uncaught exception Error with message Function name must be a string thrown in composer/vendor/menatwork/realurl/system/modules/realurl/RealUrl.php on line 107

#0 system/modules/core/drivers/DC_Table.php(3769): RealUrl->labelPage(Array, 'my-domain.de', Object(Contao\DC_Table), '', false, false)
#1 system/modules/core/drivers/DC_Table.php(3431): Contao\DC_Table->generateTree('tl_page', '69', Array, true, -20, false, false, false, false)
#2 system/modules/core/drivers/DC_Table.php(367): Contao\DC_Table->treeView()
#3 system/modules/core/classes/Backend.php(650): Contao\DC_Table->showAll()
#4 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('page')
#5 contao/main.php(20): Contao\BackendMain->run()
#6 {main}
```

**Comment by kozi** [comment]
Solution?!: https://secure.php.net/manual/de/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect

**Comment by kozi** [comment]
Changing https://github.com/menatwork-ia/realurl/blob/master/system/modules/realurl/RealUrl.php#L107
to 
`$label = $this->{$value[0]}->{$value[1]}($row, $label, $dc, $imageAttribute, $blnReturnImage, $blnProtected);`

should fix the problem in PHP7 and is backwards compatible with PHP5
